Bugfix updating versioned tags
EndlessSkyCommunity/endless-sky-plugins pull request #131
Opened 2022-03-05 17:18 UTC by samrocketman

All types of tag versions
-------------------------

First thing I did was determin all the ways tags are versioned excluding commit hashes.

```bash
$ grep '^version:' manifests/* | grep -v '[0-9a-f]\{40\}' | sed 's/.*: \?//'
v0.9.14
1.2.0
v0.1.7
1.0.0
v0.2.0
'1.0'
'1.2'
v1.0
'2.2'
v0.9.14
v0.10.10
0.9.14.14.2
0.9.14.7
v0.1.2
v1.6
```

Since we want to support N-depth version numbers it makes sense to sort with a recursive comparison and take the highest version from the sorted list.

Set a new convention for tags
-----------------------------

Rather than trying to coerce version strings out of arbitrary tags we can dictate that version numbers from this point must optionally start with a `v` prefix and be a set of dot-separated numbers.  e.g. `v1.2.3` and `1.2.3` are both considered valid version numbers.

This new convention will not conflict with existing plugins because in the list above containing all types of version numbers you can see that this dictated convention already exists.

Because of this we can simplify the code for discovering versions quite a bit instead of attempting to catch use cases which do not exist (i.e. coerce versions from arbitrary character tags).

Found a problem with Midnight Scrapyard
---------------------------------------

With the autoupdate.py script fixed to allow N-depth version numbers, the latest version discovered is `0.19.14.1` (note `0.19` and not `0.9`).  I think this is a mistake and once fixed the autoupdate will work normally for Midnight Scrapyard.

I don't think we should code around this mistake but instead ask the Midnight Scrapyard plugin to fix their versions.

Here's a reference to the bad version number (it may 404 later if it gets deleted).

https://github.com/MidnightPlugins/Midnight-Scrapyard/tree/0.19.14.1

Testing the code
----------------

I bootstrapped a Docker-based development environment similar to pull request https://github.com/EndlessSkyCommunity/endless-sky-plugins/pull/120

I then ran the following one-liner to update all projects using the new script.  It worked for all versions as intended.

    find manifests -type f -print0 | xargs -0 -n1 ./scripts/autoupdate.py

2022-03-05 22:38 UTC, MCOfficer requested changes
Much better than my version, including better documentation.

One thing i'd like to be covered is version suffixes, for example `0.1-alpha2`. In this case we'd probably want to sort the suffix (`alpha2`) alphabetically.

2022-03-06 02:08 UTC, samrocketman commented
> One thing i'd like to be covered is version suffixes, for example `0.1-alpha2`. In this case we'd probably want to sort the suffix (`alpha2`) alphabetically.

Are you sure you want this?  It's not a lot of extra effort to add this.  However, I caution supporting it because there's a lot of variance in how people across different plugins support versions today.  There's already more than 5 different formats (which isn't a huge deal because of regex).  How much is `alpha`/`beta` really used in the Endless Sky community?  From what I've seen I haven't seen it used anywhere.

2022-03-06 02:25 UTC, MidnightPlugins commented
Changed Scrapyard error tag to 0.9.14.1

Thanks.

2022-03-06 02:29 UTC, samrocketman commented
> Changed Scrapyard error tag to 0.9.14.1

When you get a chance can you delete the [old tag](https://github.com/MidnightPlugins/Midnight-Scrapyard/tree/0.19.14.1).  You can do it the following way:

    git push origin :refs/tags/0.19.14.1

2022-03-06 03:10 UTC, samrocketman commented
@MCOfficer since adding support for suffix was a 2 line change I went ahead and pushed a commit.  See my commit and additional code comments.  I had to be a bit more verbose because the code is becoming less readable as we're adding format variance.

2022-03-06 14:02 UTC, MidnightPlugins commented
deleted the bad Scrapyard tag and old "v" tags

2022-03-06 14:02 UTC, MidnightPlugins commented
deleted the bad Scrapyard tag and old "v" tags

2022-03-07 00:10 UTC, MCOfficer approved these changes

2022-03-07 00:10 UTC, merged