Added Easier Korath Automatons
EndlessSkyCommunity/endless-sky-plugins pull request #27
Opened 2021-04-26 12:45 UTC by kestrel1110

Added my plugin Easier Korath Automatons, which makes capping Sestor & Mereti easier by lowering self-destruct chances.

2021-04-26 12:58 UTC, MCOfficer requested changes

2021-04-26 12:58 UTC, MCOfficer commented on manifests/Easier Korath Automatons.yaml
> +iconUrl: https://raw.githubusercontent.com/kestrel1110/Easier-Korath-Automatons/master/icon.png
This should also be versioned, and for style points match the `iconUrl` in `autoupdate`
```suggestion
iconUrl: https://github.com/kestrel1110/Easier-Korath-Automatons/raw/1.0.0/icon.png
```

2021-04-26 12:58 UTC, MCOfficer commented on manifests/Easier Korath Automatons.yaml
> +  type: commit
You're using version 1.0.0, so you probably want `tag`
```suggestion
  type: tag
```

2021-04-27 03:07 UTC, kestrel1110 commented
Thanks for the info, it's all updated now.

2021-04-27 06:47 UTC, merged